export const SENDING_MESSAGE = 'SENDING_MESSAGE';
export const SENT_MESSAGE = 'SENT_MESSAGE';
export const RECEIVED_MESSAGE = 'RECEIVED_MESSAGE';
export const SET_SELECTED_RESPONSE = 'SET_SELECTED_RESPONSE';
export const RESET = 'RESET';
export const TECHNICAL_ERROR = 'TECHNICAL_ERROR';